import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "~/components/theme-provider";
import { ModeToggle } from "~/components/mode-toggle";
import { GlobalStateProvider } from "~/components/GlobalStateContext";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>
            <GlobalStateProvider>
              <main className="flex min-h-screen flex-col items-center justify-center gap-4 text-white">
                <ModeToggle />
                {children}
              </main>
            </GlobalStateProvider>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
